feat: implement refocusing trigger-element after closing modal
necolas/react-native-web pull request #1821
Opened 2020-11-25 16:17 UTC by RafikiTiki

In a project which I'm part of right now we're working towards compatibility with WCAG spec. When using current implementation of <Modal /> component I've seen that you've handled focus trap problem in very clean manner but there's one more thing that I believe that should be implemented to be even more compliant with the spec.

> A Web page implements modal dialogs via scripting. When the trigger button is activated, a dialog opens and focus is set to the first interactive element in the dialog. As long as the dialog is open, focus is limited to the elements of the dialog. **When the dialog is dismissed, focus returns to the button or the element following the button.**

source: https://www.w3.org/WAI/WCAG21/Understanding/focus-order Examples point 3

This PR is implementing such _refocus element that triggered modal after closing it_ mechanism.

2020-12-03 20:54 UTC, necolas requested changes
We will need unit tests for this behavior

2020-12-03 20:54 UTC, necolas commented on packages/react-native-web/src/exports/Modal/ModalFocusTrap.js
> +        if (lastFocusedElementOutsideTrap.current) {
This value needs to be stored in the closure rather than read in the cleanup callback

2020-12-03 20:54 UTC, necolas commented on packages/react-native-web/src/exports/Modal/ModalFocusTrap.js
> +          UIManager.focus(lastFocusedElementOutsideTrap.current);
Probably need to check if this element is still in the document

2021-01-19 11:02 UTC, RafikiTiki commented
@necolas sorry that it did take so long but I've finally found some time to update the PR. I've refactored things you've pointed out and also implemented tests for refocusing mechanism. Have a good day :)

2021-01-29 00:36 UTC, necolas commented
Thanks!

2021-01-29 00:37 UTC, necolas approved these changes

2021-01-29 00:37 UTC, closed without merging