[WIP] Add TS support to react-native
necolas/react-native-web pull request #2702
Opened 2024-07-24 15:13 UTC by fabioh8010

TODO

2024-07-26 08:16 UTC, blazejkustra requested changes

2024-07-26 08:16 UTC, blazejkustra commented on packages/react-native-web/package.json
> +  }
I don't think we need to add this line as part of this PR

2024-07-26 08:16 UTC, blazejkustra commented on packages/react-native-web/package.json
> +    "build:typescript": "tsc",
Let's remove this step and tsconfig file, I think it's not needed 👍

2024-07-26 08:20 UTC, blazejkustra commented
Awesome work @fabioh8010! Let's update the description to address why the PR is needed in the first place, and post it [here](https://github.com/necolas/react-native-web/issues/832) and [here](https://github.com/necolas/react-native-web/issues/1684) to gather some 👀

2024-07-26 11:35 UTC, blazejkustra approved these changes

2024-07-26 15:51 UTC, necolas commented
I'm not going to merge and maintain a separate set of TS types. Sorry

2024-08-07 19:58 UTC, blazejkustra commented
> I'm not going to merge and maintain a separate set of TS types. Sorry

That is fine 😄 This PR can be closed now, as we just added TS definitions for RNW and extended RN types in [DefinietlyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70147)!

2024-08-07 20:12 UTC, blazejkustra commented
This PR can be closed now, as we just added TS definitions for RNW and extended RN types in [DefinietlyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70147). 

### Installation
Simply install the types with `npm run install @types/react-native-web` and supply `react-native-web` as a member of the types compiler option:
```ts
{
  "compilerOptions": {
    "types": ["react-native-web"]
  }
}
```

2024-08-08 15:32 UTC, closed without merging

2024-08-08 15:34 UTC, fabioh8010 commented
Closing as per discussed above, we will create a PR with the instructions to this repo soon!